import type { TemplateConfig } from '../types';

// ─── Surat Perjanjian Jual Beli ───────────────────────────────────────────────
// PAID | Kategori: Jual Beli | price: 15000 | No watermark (after payment)
// ─────────────────────────────────────────────────────────────────────────────

export const suratPerjanjianJualBeliTemplate: TemplateConfig = {
  id: 'surat-perjanjian-jual-beli',
  name: 'Surat Perjanjian Jual Beli',
  description: 'Surat perjanjian resmi antara penjual dan pembeli yang memiliki kekuatan hukum untuk berbagai transaksi jual beli.',
  category: 'jual-beli',
  icon: 'handshake',
  price: 15000, // Rp 15.000 — BERBAYAR
  previewComponent: 'SuratPerjanjianJualBeliPreview',
  pdfComponent: 'SuratPerjanjianJualBeliPDF',
  steps: [
    {
      id: 'pihak-pertama',
      title: 'Data Pihak Pertama',
      description: 'Isi data lengkap penjual (Pihak Pertama).',
      fields: [
        {
          name: 'namaPenjual',
          type: 'text',
          label: 'Nama Lengkap Penjual',
          placeholder: 'Masukkan nama sesuai KTP',
          required: true,
          colSpan: 2,
        },
        {
          name: 'nikPenjual',
          type: 'number',
          label: 'NIK Penjual',
          placeholder: '16 digit NIK',
          required: true,
          colSpan: 2,
          validation: { minLength: 16, maxLength: 16, message: 'NIK harus 16 digit' },
        },
        {
          name: 'alamatPenjual',
          type: 'textarea',
          label: 'Alamat Lengkap Penjual',
          placeholder: 'Jalan, RT/RW, Kelurahan, Kecamatan, Kota/Kabupaten',
          required: true,
          colSpan: 2,
        },
        {
          name: 'pekerjaanPenjual',
          type: 'text',
          label: 'Pekerjaan Penjual',
          placeholder: 'Cth: Wiraswasta',
          required: false,
          colSpan: 2,
        },
      ],
    },
    {
      id: 'pihak-kedua',
      title: 'Data Pihak Kedua',
      description: 'Isi data lengkap pembeli (Pihak Kedua).',
      fields: [
        {
          name: 'namaPembeli',
          type: 'text',
          label: 'Nama Lengkap Pembeli',
          placeholder: 'Masukkan nama sesuai KTP',
          required: true,
          colSpan: 2,
        },
        {
          name: 'nikPembeli',
          type: 'number',
          label: 'NIK Pembeli',
          placeholder: '16 digit NIK',
          required: true,
          colSpan: 2,
          validation: { minLength: 16, maxLength: 16, message: 'NIK harus 16 digit' },
        },
        {
          name: 'alamatPembeli',
          type: 'textarea',
          label: 'Alamat Lengkap Pembeli',
          placeholder: 'Jalan, RT/RW, Kelurahan, Kecamatan, Kota/Kabupaten',
          required: true,
          colSpan: 2,
        },
        {
          name: 'pekerjaanPembeli',
          type: 'text',
          label: 'Pekerjaan Pembeli',
          placeholder: 'Cth: Karyawan Swasta',
          required: false,
          colSpan: 2,
        },
      ],
    },
    {
      id: 'detail-perjanjian',
      title: 'Detail Perjanjian',
      description: 'Isi detail objek perjanjian dan bubuhkan tanda tangan.',
      fields: [
        {
          name: 'objekJualBeli',
          type: 'text',
          label: 'Objek yang Diperjualbelikan',
          placeholder: 'Cth: Tanah dan bangunan, Kendaraan Honda Beat 2020, Laptop ASUS ...',
          required: true,
          colSpan: 2,
        },
        {
          name: 'hargaJualBeli',
          type: 'number',
          label: 'Harga Kesepakatan (Rp)',
          placeholder: 'Cth: 50000000',
          required: true,
          colSpan: 1,
        },
        {
          name: 'metodePembayaran',
          type: 'select',
          label: 'Metode Pembayaran',
          required: true,
          colSpan: 1,
          options: [
            { value: 'tunai', label: 'Tunai / Cash' },
            { value: 'transfer', label: 'Transfer Bank' },
            { value: 'cicilan', label: 'Cicilan' },
            { value: 'lainnya', label: 'Lainnya' },
          ],
        },
        {
          name: 'deskripsiObjek',
          type: 'textarea',
          label: 'Deskripsi Detail Objek',
          placeholder: 'Cth: Tanah seluas 100m2 yang terletak di Jl. Merdeka No.10, dengan sertifikat HGB No. 123...',
          required: false,
          colSpan: 2,
        },
        {
          name: 'ketentuanTambahan',
          type: 'textarea',
          label: 'Ketentuan Tambahan (Opsional)',
          placeholder: 'Cth: Penyerahan objek dilakukan pada tanggal 30 hari setelah pembayaran lunas...',
          required: false,
          colSpan: 2,
        },
        {
          name: 'kotaSurat',
          type: 'text',
          label: 'Kota Pembuatan Surat',
          placeholder: 'Cth: Jakarta',
          required: true,
          colSpan: 1,
        },
        {
          name: 'tanggalSurat',
          type: 'date',
          label: 'Tanggal Surat',
          required: true,
          colSpan: 1,
        },
        {
          name: 'tandaTanganPenjual',
          type: 'signature',
          label: 'Tanda Tangan Pihak Pertama (Penjual)',
          required: false,
          colSpan: 1,
        },
        {
          name: 'tandaTanganPembeli',
          type: 'signature',
          label: 'Tanda Tangan Pihak Kedua (Pembeli)',
          required: false,
          colSpan: 1,
        },
      ],
    },
  ],
};

