import type { TemplateConfig } from '../types';

export const suratPengantarPenelitianTemplate: TemplateConfig = {
  id: 'surat-pengantar-penelitian',
  name: 'Surat Pengantar Penelitian/Skripsi',
  description: 'Surat permohonan izin dari mahasiswa ke instansi luar untuk melakukan wawancara, observasi, atau pengambilan data riset/skripsi.',
  category: 'sekolah',
  icon: 'science',
  price: 0,
  previewComponent: 'SuratPengantarPenelitianPreview',
  pdfComponent: 'SuratPengantarPenelitianPDF',
  steps: [
    {
      id: 'data-surat',
      title: 'Data Penelitian',
      description: 'Lengkapi informasi surat pengantar penelitian.',
      fields: [
        {
          name: 'namaMahasiswa',
          type: 'text',
          label: 'Nama Lengkap Peneliti / Mahasiswa',
          placeholder: 'Cth: Eka Nugraha',
          required: true,
          colSpan: 2,
        },
        {
          name: 'nim',
          type: 'text',
          label: 'NIM',
          placeholder: 'Cth: 2018009012',
          required: false,
          colSpan: 1,
        },
        {
          name: 'jurusan',
          type: 'text',
          label: 'Program Studi / Jurusan',
          placeholder: 'Cth: S1 Psikologi',
          required: true,
          colSpan: 1,
        },
        {
          name: 'namaKampus',
          type: 'text',
          label: 'Nama Perguruan Tinggi',
          placeholder: 'Cth: Universitas Padjadjaran',
          required: true,
          colSpan: 2,
        },
        {
          name: 'judulPenelitian',
          type: 'textarea',
          label: 'Judul Penelitian / Skripsi',
          placeholder: 'Cth: "Pengaruh Media Sosial terhadap Tingkat Kecemasan Remaja di Era Digital"',
          required: true,
          colSpan: 2,
        },
        {
          name: 'instansiTujuan',
          type: 'text',
          label: 'Instansi / Lembaga yang Dituju',
          placeholder: 'Cth: PT. Bank Rakyat Indonesia (Persero) Tbk. Cabang Bandung',
          required: true,
          colSpan: 2,
        },
        {
          name: 'jenisKegiatan',
          type: 'text',
          label: 'Jenis Kegiatan Penelitian',
          placeholder: 'Cth: Wawancara mendalam dan pengisian kuesioner',
          required: true,
          colSpan: 2,
        },
        {
          name: 'tanggalMulai',
          type: 'date',
          label: 'Tanggal Mulai Penelitian',
          required: true,
          colSpan: 1,
        },
        {
          name: 'tanggalSelesai',
          type: 'date',
          label: 'Tanggal Selesai Penelitian',
          required: true,
          colSpan: 1,
        },
        {
          name: 'kotaSurat',
          type: 'text',
          label: 'Kota Pembuatan Surat',
          placeholder: 'Cth: Bandung',
          required: true,
          colSpan: 1,
        },
        {
          name: 'tanggalSurat',
          type: 'date',
          label: 'Tanggal Surat',
          required: true,
          colSpan: 1,
        },
        {
          name: 'tandaTangan',
          type: 'signature',
          label: 'Tanda Tangan Peneliti',
          required: false,
          colSpan: 2,
        },
      ],
    },
  ],
};

