import type { TemplateConfig } from '../types';

export const suratPermohonanRekomendasiTemplate: TemplateConfig = {
  id: 'surat-permohonan-rekomendasi',
  name: 'Surat Permohonan Rekomendasi Guru/Dosen',
  description: 'Surat dari siswa/mahasiswa kepada guru atau dosen agar bersedia menulis surat rekomendasi untuk mendaftar beasiswa atau pekerjaan.',
  category: 'sekolah',
  icon: 'recommend',
  price: 0,
  previewComponent: 'SuratPermohonanRekomendasiPreview',
  pdfComponent: 'SuratPermohonanRekomendasiPDF',
  steps: [
    {
      id: 'data-surat',
      title: 'Data Permohonan Rekomendasi',
      description: 'Lengkapi informasi surat permohonan rekomendasi.',
      fields: [
        {
          name: 'namaPemohon',
          type: 'text',
          label: 'Nama Lengkap Pemohon',
          placeholder: 'Cth: Bagas Wirawan',
          required: true,
          colSpan: 2,
        },
        {
          name: 'nim',
          type: 'text',
          label: 'NIM / NIS',
          placeholder: 'Cth: 2019004567',
          required: false,
          colSpan: 1,
        },
        {
          name: 'jurusan',
          type: 'text',
          label: 'Jurusan / Program Studi',
          placeholder: 'Cth: Ilmu Komunikasi',
          required: true,
          colSpan: 1,
        },
        {
          name: 'namaInstitusi',
          type: 'text',
          label: 'Nama Institusi Pendidikan',
          placeholder: 'Cth: Universitas Brawijaya',
          required: true,
          colSpan: 2,
        },
        {
          name: 'namaGuruDosen',
          type: 'text',
          label: 'Nama Guru / Dosen yang Dituju',
          placeholder: 'Cth: Dr. Budi Rahardjo, M.Si.',
          required: true,
          colSpan: 2,
        },
        {
          name: 'tujuanRekomendasi',
          type: 'text',
          label: 'Tujuan Penggunaan Rekomendasi',
          placeholder: 'Cth: Pendaftaran Beasiswa LPDP 2025 / Melamar Kerja di PT. ABC',
          required: true,
          colSpan: 2,
        },
        {
          name: 'alasan',
          type: 'textarea',
          label: 'Alasan Memilih Guru/Dosen Tersebut',
          placeholder: 'Cth: Karena Bapak/Ibu adalah dosen pembimbing saya dan mengenal kemampuan akademik saya dengan baik.',
          required: false,
          colSpan: 2,
        },
        {
          name: 'kotaSurat',
          type: 'text',
          label: 'Kota Pembuatan Surat',
          placeholder: 'Cth: Malang',
          required: true,
          colSpan: 1,
        },
        {
          name: 'tanggalSurat',
          type: 'date',
          label: 'Tanggal Surat',
          required: true,
          colSpan: 1,
        },
        {
          name: 'tandaTangan',
          type: 'signature',
          label: 'Tanda Tangan Pemohon',
          required: false,
          colSpan: 2,
        },
      ],
    },
  ],
};

