import type { TemplateConfig } from '../types';

export const suratCutiAkademikTemplate: TemplateConfig = {
  id: 'surat-cuti-akademik',
  name: 'Surat Permohonan Cuti Akademik',
  description: 'Surat resmi mahasiswa kepada pihak kampus untuk mengambil cuti/libur semester sementara waktu.',
  category: 'sekolah',
  icon: 'calendar_month',
  price: 0,
  previewComponent: 'SuratCutiAkademikPreview',
  pdfComponent: 'SuratCutiAkademikPDF',
  steps: [
    {
      id: 'data-surat',
      title: 'Data Permohonan Cuti',
      description: 'Lengkapi informasi permohonan cuti akademik Anda.',
      fields: [
        {
          name: 'namaMahasiswa',
          type: 'text',
          label: 'Nama Lengkap Mahasiswa',
          placeholder: 'Cth: Rizky Pratama',
          required: true,
          colSpan: 2,
        },
        {
          name: 'nim',
          type: 'text',
          label: 'NIM',
          placeholder: 'Cth: 2021001234',
          required: true,
          colSpan: 1,
        },
        {
          name: 'jurusan',
          type: 'text',
          label: 'Program Studi / Jurusan',
          placeholder: 'Cth: Teknik Informatika',
          required: true,
          colSpan: 1,
        },
        {
          name: 'semester',
          type: 'text',
          label: 'Semester Saat Ini',
          placeholder: 'Cth: 5',
          required: true,
          colSpan: 1,
        },
        {
          name: 'namaKampus',
          type: 'text',
          label: 'Nama Perguruan Tinggi',
          placeholder: 'Cth: Universitas Gadjah Mada',
          required: true,
          colSpan: 1,
        },
        {
          name: 'semesterCuti',
          type: 'text',
          label: 'Semester yang Diambil Cuti',
          placeholder: 'Cth: Semester 6 (Genap 2024/2025)',
          required: true,
          colSpan: 2,
        },
        {
          name: 'alasanCuti',
          type: 'textarea',
          label: 'Alasan Pengajuan Cuti',
          placeholder: 'Cth: Karena kondisi kesehatan yang kurang memungkinkan dan disarankan dokter untuk beristirahat total selama satu semester.',
          required: true,
          colSpan: 2,
        },
        {
          name: 'kotaSurat',
          type: 'text',
          label: 'Kota Pembuatan Surat',
          placeholder: 'Cth: Yogyakarta',
          required: true,
          colSpan: 1,
        },
        {
          name: 'tanggalSurat',
          type: 'date',
          label: 'Tanggal Surat',
          required: true,
          colSpan: 1,
        },
        {
          name: 'tandaTangan',
          type: 'signature',
          label: 'Tanda Tangan Mahasiswa',
          required: false,
          colSpan: 2,
        },
      ],
    },
  ],
};

