import type { TemplateConfig } from '../types';

export const suratPeminjamanFasilitasTemplate: TemplateConfig = {
  id: 'surat-peminjaman-fasilitas',
  name: 'Surat Peminjaman Fasilitas/Ruangan',
  description: 'Surat dari organisasi siswa/mahasiswa (OSIS/BEM/Ekskul) kepada pihak sekolah/kampus untuk meminjam aula, lapangan, atau peralatan.',
  category: 'sekolah',
  icon: 'meeting_room',
  price: 0,
  previewComponent: 'SuratPeminjamanFasilitasPreview',
  pdfComponent: 'SuratPeminjamanFasilitasPDF',
  steps: [
    {
      id: 'data-surat',
      title: 'Data Peminjaman',
      description: 'Lengkapi informasi permohonan peminjaman fasilitas.',
      fields: [
        {
          name: 'namaOrganisasi',
          type: 'text',
          label: 'Nama Organisasi / Komunitas',
          placeholder: 'Cth: BEM Fakultas Teknik / OSIS SMA 1 / Ekskul Pramuka',
          required: true,
          colSpan: 2,
        },
        {
          name: 'namaKetua',
          type: 'text',
          label: 'Nama Ketua / Penanggung Jawab',
          placeholder: 'Cth: Muhammad Faisal',
          required: true,
          colSpan: 1,
        },
        {
          name: 'kontakPJ',
          type: 'text',
          label: 'No. HP Penanggung Jawab',
          placeholder: 'Cth: 08123456789',
          required: false,
          colSpan: 1,
        },
        {
          name: 'namaInstitusi',
          type: 'text',
          label: 'Nama Sekolah / Kampus',
          placeholder: 'Cth: Universitas Airlangga / SMA Negeri 2 Surabaya',
          required: true,
          colSpan: 2,
        },
        {
          name: 'fasilitasDipinjam',
          type: 'text',
          label: 'Fasilitas yang Dipinjam',
          placeholder: 'Cth: Aula Utama / Lapangan Basket / Proyektor LCD',
          required: true,
          colSpan: 2,
        },
        {
          name: 'namaKegiatan',
          type: 'text',
          label: 'Nama Kegiatan',
          placeholder: 'Cth: Seminar Nasional Teknologi 2025',
          required: true,
          colSpan: 2,
        },
        {
          name: 'tanggalPeminjaman',
          type: 'date',
          label: 'Tanggal Peminjaman',
          required: true,
          colSpan: 1,
        },
        {
          name: 'waktuPeminjaman',
          type: 'text',
          label: 'Waktu Peminjaman',
          placeholder: 'Cth: 08.00 – 17.00 WIB',
          required: true,
          colSpan: 1,
        },
        {
          name: 'kotaSurat',
          type: 'text',
          label: 'Kota Pembuatan Surat',
          placeholder: 'Cth: Surabaya',
          required: true,
          colSpan: 1,
        },
        {
          name: 'tanggalSurat',
          type: 'date',
          label: 'Tanggal Surat',
          required: true,
          colSpan: 1,
        },
        {
          name: 'tandaTangan',
          type: 'signature',
          label: 'Tanda Tangan Ketua / PJ',
          required: false,
          colSpan: 2,
        },
      ],
    },
  ],
};

